'use client'
import { Provider } from 'react-redux'
import Header from './components/Header'
import './globals.css'
import { Montserrat } from 'next/font/google'
import store from './redux/store'
import Footer from './components/Footer'
import { Toaster } from 'react-hot-toast'

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-montserrat',
})

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                className={`${montserrat.variable} font-montserrat min-h-screen flex flex-col justify-between`}
            >
                <Provider store={store}>
                    <Header />
                    {children}
                    <Footer />
                    <Toaster />
                </Provider>
            </body>
        </html>
    )
}
